### ISSUE TITLE
volmaster REST endpoints need some rework

### ISSUE THREAD

**Issue by mapuri** [contiv/volplugin#229]
tracking the items from comments here: https://github.com/contiv/volplugin/pull/228/files#r59947447

(edited by @erikh)

* [x] for everything that uses etcd straight from volcli, please implement the appropriate REST call in the volmaster instead, and point volcli to use it.
* [x] Fix routes to be clearer (covered by #255)
* [x] Clean up existing endpoints if necessary -- structs in use should be typed structs and not f.e. maps.
* [x] Normalize http.Client usage so that a shared client is used.
* [ ] Remove all `fmt.Sprintf` calls that generate URLs and use a URL constructor instead (encoding/url maybe?)
* [x] Make it possible to get mount information for volumes (implemented by #280)
* [x] Make it possible to get mount information for snapshots
* [x] Switch remove handlers to DELETE (implemented by #280 already)

**Comment by mapuri** [comment]
List of work items:
- [ ] make GET endpoints consistent - will be addressed by #255 
- [ ]  make POST endpoints consistent

**Comment by erikh** [comment]
Closing this; it looks like we're ready to go with these patches and they made it into the v0.1 release. We will revisit the client issue in a separate ticket.
